CREATE TABLE cars(
 id INT NOT NULL AUTO_INCREMENT,
 make VARCHAR(255) NOT NULL,
 model VARCHAR(255) NOT NULL,
 year VARCHAR(255) NOT NULL,
 price VARCHAR(255) NOT NULL,
 decription VARCHAR (500) NOT NULL,
 imgUrl VARCHAR(500) NOT NULL,
 userId VARCHAR(255) NOT NULL,
 PRIMARY KEY (id) 
)

-- DROP TABLE cars